/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import Fuentes.Moonglade;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Pc
 */
public class Administrador extends javax.swing.JFrame {
    public static FileWriter flwriter = null; 
   public static String username, passcompare;
   public static char[] password; 
   public static long pos = 0, linex=0;
    Moonglade tipoFuente;
    //COMENTARIO OTRA VEZ EQUISDE
    
    public Administrador() {
        initComponents();
        jop.setVisible(false);
        tipoFuente= new Moonglade();
        jlb1.setFont(tipoFuente.fuente(tipoFuente.MOON, 3, 11));
        jlb2.setFont(tipoFuente.fuente(tipoFuente.MOON,3, 11));
            this.setLocationRelativeTo(null);
    }
    
    public void inicioSesion(){
        username = jtfUser.getText();
        password = jtfpwd.getPassword();
        passcompare = String.valueOf(password);
    }
 public void buscoArchivo(){ 
        String xusername="",xpassword="";
        try {  //crea el flujo para escribir en el archivo
          File flwriter = new File("C:\\BD\\ADM.txt");
          Scanner leer_archivo = null;
          leer_archivo = new Scanner(flwriter);
          while(leer_archivo.hasNextLine()){
             String Linea_archivo = leer_archivo.nextLine();
             Scanner delimitar = new Scanner(Linea_archivo);
             delimitar.useDelimiter("\\s*,\\s*");
             xusername = delimitar.next();
             xpassword = delimitar.next();
             System.out.println(xusername + "\t" + xpassword);
             if(username.equals(xusername) && passcompare.equals(xpassword)){
                SEDAN_ADMIN flujo= new SEDAN_ADMIN();
                flujo.setVisible(true);
                JOptionPane.showMessageDialog(null,"BIENVENIDO");
                dispose();   
                 break;
             }
             if(!leer_archivo.hasNextLine()){
                 JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrectos");
             }
          }
       } catch (IOException e) {
            e.printStackTrace();
         } finally {  // consolida el cierre de archivo con transacciones
              if (flwriter != null) {
                 try {//cierra el flujo principal
                    flwriter.close();
                    System.exit( 0 );
                 } catch (IOException e) {
                      e.printStackTrace();
                   }
              }
           }
 }

    /**Admin
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb1 = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jlb2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfpwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jop = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlb1.setForeground(new java.awt.Color(255, 255, 255));
        jlb1.setText("USUARIO");
        getContentPane().add(jlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));
        getContentPane().add(jtfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 248, -1));

        jlb2.setForeground(new java.awt.Color(255, 255, 255));
        jlb2.setText("CONTRASEÑA");
        getContentPane().add(jlb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jButton3.setText("INICIAR SESIÓN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user1_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        getContentPane().add(jtfpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 230, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jop, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        interfaz flujo= new interfaz();
        flujo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
inicioSesion();
buscoArchivo();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JOptionPane jop;
    private javax.swing.JTextField jtfUser;
    private javax.swing.JPasswordField jtfpwd;
    // End of variables declaration//GEN-END:variables
}
