/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import Fuentes.Moonglade;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.io.FileWriter;
/**
 *
 * @author Pc
 */

public class C_SEDAN extends javax.swing.JFrame {
public static FileWriter flwriter = null;
public static String auto, ncadena="NOMBRE\tEDAD\tLICENCIA\tUSUARIO\n";
    /**
     * Creates new form C_SEDAN
     */
    Moonglade tipoFuente;
    public C_SEDAN() {
        initComponents();
        tipoFuente= new Moonglade();
        jlb1.setFont(tipoFuente.fuente(tipoFuente.MOON, 3, 11));
        jlb2.setFont(tipoFuente.fuente(tipoFuente.MOON, 3, 25));
        this.setLocationRelativeTo(null);
    }
public void buscoArchivo(){ 
        String xname ="", xlicense="", xage="", xusername="",xauto="";
        try {  //crea el flujo para escribir en el archivo
          File flwriter = new File("C:\\BD\\CONTRATOS.txt");
          Scanner leer_archivo = null;
          leer_archivo = new Scanner(flwriter);
          while(leer_archivo.hasNextLine()){
             String Linea_archivo = leer_archivo.nextLine();
             Scanner delimitar = new Scanner(Linea_archivo);
             delimitar.useDelimiter("\\s*,\\s*");
             xname = delimitar.next();
             xage = delimitar.next();
             xlicense = delimitar.next();
             xusername = delimitar.next();
             xauto = delimitar.next(); 
             if(auto.equals(xauto)){
                 ncadena=ncadena+xname+"\t"+xage+"\t"+xlicense+"\t"+xusername+"\n";
                System.out.println(xname + "\t" + xage + "\t" + xlicense + "\t\t" + xusername + "\t" + xauto);
             }
          }
       } catch (IOException e) {
            e.printStackTrace();
         } finally {  // consolida el cierre de archivo con transacciones
              if (flwriter != null) {
                 try {//cierra el flujo principal
                    flwriter.close();
                    System.exit( 0 );
                 } catch (IOException e) {
                      e.printStackTrace();
                   }
              }
           }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf1 = new javax.swing.JTextField();
        jbt1 = new javax.swing.JButton();
        jlb1 = new javax.swing.JLabel();
        jbt2 = new javax.swing.JButton();
        jlb2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, 30));

        jbt1.setText("CONSULTAR CONTRATOS");
        jbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jlb1.setForeground(new java.awt.Color(255, 255, 255));
        jlb1.setText("MODELO");
        getContentPane().add(jlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jbt2.setText("ATRAS");
        jbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jlb2.setForeground(new java.awt.Color(255, 255, 255));
        jlb2.setText("CONTRATOS");
        getContentPane().add(jlb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jta.setColumns(20);
        jta.setRows(5);
        jScrollPane2.setViewportView(jta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 400, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jOptionPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf1ActionPerformed

    private void jbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt2ActionPerformed
SEDAN_ADMIN flujo= new SEDAN_ADMIN();
flujo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt2ActionPerformed

    private void jbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt1ActionPerformed
auto=jtf1.getText();
buscoArchivo();
jta.setText(ncadena);
    }//GEN-LAST:event_jbt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_SEDAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_SEDAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_SEDAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_SEDAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_SEDAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbt1;
    private javax.swing.JButton jbt2;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JTextArea jta;
    private javax.swing.JTextField jtf1;
    // End of variables declaration//GEN-END:variables
}
