/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import static interfaz.Cliente.yusername;
import static interfaz.Cliente.ylicense;

/**
 *
 * @author Pc
 */

public class CONTRATO extends javax.swing.JFrame {
    public static FileWriter flwriter = null; 
   public static String name;
   public static String age;
   public static String license;
   public static String username;
   public static String ncadena="";
   public static String auto;

    public CONTRATO() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void asignar(){
      ncadena="";
      ncadena+=name + ",";
      ncadena+=age+ ",";
      ncadena+=ylicense + ",";
      ncadena+=yusername + ",";
      ncadena+=auto;      
    }
    public void registroArchivo(){
       String xname ="", xlicense="", xage="", xusername="", xpassword=""; 
        try {  //crea el flujo para escribir en el archivo
          File flwriter = new File("C:\\BD\\EQ05.txt");
          Scanner leer_archivo = null;
          leer_archivo = new Scanner(flwriter);
          while(leer_archivo.hasNextLine()){
             String Linea_archivo = leer_archivo.nextLine();
             Scanner delimitar = new Scanner(Linea_archivo);
             delimitar.useDelimiter("\\s*,\\s*");
             xname = delimitar.next();
             xage = delimitar.next();
             xlicense = delimitar.next();
             xusername = delimitar.next();
             xpassword = delimitar.next();
             if(yusername.equals(xusername) && ylicense.equals(xlicense)){
                name=xname;
                age=xage;
                 break;
             }
          }
       } catch (IOException e) {
            e.printStackTrace();
         } finally {  // consolida el cierre de archivo con transacciones
              if (flwriter != null) {
                 try {//cierra el flujo principal
                    flwriter.close();
                    System.exit( 0 );
                 } catch (IOException e) {
                      e.printStackTrace();
                   }
              }
           }
}    
    public void cambiarArchivo(){
       try {
                flwriter = new FileWriter("C:\\BD\\CONTRATOS.txt",true);
                flwriter.write(ncadena + "\n");
                flwriter.close(); 
            } catch (IOException e) {
                e.printStackTrace();
            } finally {  
          if (flwriter != null) {
              try {
                 flwriter.close();
              } catch (IOException e) { 
                    e.printStackTrace();  
                }
          }
        }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt1.setColumns(20);
        jt1.setRows(5);
        jScrollPane1.setViewportView(jt1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 260));

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
registroArchivo();
asignar();
cambiarArchivo();
Sedan flujo =new Sedan();
flujo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONTRATO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONTRATO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONTRATO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONTRATO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONTRATO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jt1;
    // End of variables declaration//GEN-END:variables
}
