/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Fuentes.Moonglade;
import static interfaz.Cliente.ylicense;
import static interfaz.Cliente.yname;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;

/**
 *
 * @author Pc
 */
public class Sedan extends javax.swing.JFrame {

    /**
     * Creates new form Sedan
     */
    public static String auto1, precio;
Moonglade tipoFuente; 

    public Sedan() {
        initComponents();
        tipoFuente= new Moonglade();
        jlb1.setFont(tipoFuente.fuente(tipoFuente.MOON, 3, 25));
        jlb2.setFont(tipoFuente.fuente(tipoFuente.MOON,3, 11));
        jlb4.setFont(tipoFuente.fuente(tipoFuente.MOON,3, 11));
        jlbcomp.setFont(tipoFuente.fuente(tipoFuente.MOON,3, 11));
        jlbcomp1.setFont(tipoFuente.fuente(tipoFuente.MOON, 3, 11));

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbcomp1 = new javax.swing.JLabel();
        jlb4 = new javax.swing.JLabel();
        jlb2 = new javax.swing.JLabel();
        jlbcomp = new javax.swing.JLabel();
        jlb5 = new javax.swing.JLabel();
        jlb3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlb1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jlb1.setForeground(new java.awt.Color(255, 255, 255));
        jlb1.setText("SEDAN");
        getContentPane().add(jlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 200, 40));

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SEDAN.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SEDAN.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 190, 70));

        jlbcomp1.setForeground(new java.awt.Color(255, 255, 255));
        jlbcomp1.setText("COMPRAR");
        jlbcomp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbcomp1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbcomp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbcomp1MouseExited(evt);
            }
        });
        getContentPane().add(jlbcomp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jlb4.setForeground(new java.awt.Color(255, 255, 255));
        jlb4.setText("CHEVROLET AVEO");
        getContentPane().add(jlb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, 20));

        jlb2.setForeground(new java.awt.Color(255, 255, 255));
        jlb2.setText("MITSUBISHI MIRAGE");
        getContentPane().add(jlb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jlbcomp.setForeground(new java.awt.Color(255, 255, 255));
        jlbcomp.setText("COMPRAR");
        jlbcomp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbcompMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbcompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbcompMouseExited(evt);
            }
        });
        getContentPane().add(jlbcomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jlb5.setForeground(new java.awt.Color(255, 255, 255));
        jlb5.setText("$15,489");
        jlb5.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jlb5ComponentAdded(evt);
            }
        });
        getContentPane().add(jlb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jlb3.setForeground(new java.awt.Color(255, 255, 255));
        jlb3.setText("$12,140");
        jlb3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jlb3ComponentAdded(evt);
            }
        });
        getContentPane().add(jlb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        jMenu1.setText("MODELOS");

        jMenuItem1.setText("SUV");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
SUV flujo= new SUV();
        flujo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
interfaz flujo= new interfaz();
        flujo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jlbcompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbcompMouseClicked
CONTRATO flujo= new CONTRATO();
        flujo.setVisible(true);
        auto1=jlb2.getText();
        precio=jlb3.getText();
        CONTRATO.jt1.setText("CONTRATO\n\n"+yname+"\n"+ylicense+"\n*****\n"+auto1+"\n*****\n"+precio);
        CONTRATO.auto=auto1;
        dispose();
    }//GEN-LAST:event_jlbcompMouseClicked

    private void jlbcompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbcompMouseEntered
                Font font=jlbcomp.getFont();
                Map attributes=font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE,TextAttribute.UNDERLINE_ON);
                jlbcomp.setFont(font.deriveFont(attributes));
                jlbcomp.setForeground(Color.blue);
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jlbcompMouseEntered

    private void jlbcompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbcompMouseExited
                jlbcomp.setForeground(Color.white);
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                Font font = jlbcomp.getFont();
                Map attributes=font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, -1);
                jlbcomp.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_jlbcompMouseExited

    private void jlbcomp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbcomp1MouseClicked
CONTRATO flujo= new CONTRATO();
        flujo.setVisible(true);
        auto1=jlb4.getText();
        precio=jlb5.getText();
        CONTRATO.jt1.setText("CONTRATO\n\n"+yname+"\n"+ylicense+"\n*****\n"+auto1+"\n*****\n"+precio);
        CONTRATO.auto=auto1;
        dispose();
    }//GEN-LAST:event_jlbcomp1MouseClicked

    private void jlbcomp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbcomp1MouseEntered
                Font font=jlbcomp1.getFont();
                Map attributes=font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE,TextAttribute.UNDERLINE_ON);
                jlbcomp1.setFont(font.deriveFont(attributes));
                jlbcomp1.setForeground(Color.blue);
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jlbcomp1MouseEntered

    private void jlbcomp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbcomp1MouseExited
                jlbcomp1.setForeground(Color.white);
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                Font font = jlbcomp1.getFont();
                Map attributes=font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, -1);
                jlbcomp1.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_jlbcomp1MouseExited

    private void jlb5ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jlb5ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jlb5ComponentAdded

    private void jlb3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jlb3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jlb3ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sedan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sedan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sedan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sedan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sedan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JLabel jlb3;
    private javax.swing.JLabel jlb4;
    private javax.swing.JLabel jlb5;
    private javax.swing.JLabel jlbcomp;
    private javax.swing.JLabel jlbcomp1;
    // End of variables declaration//GEN-END:variables


}
